### ISSUE TITLE
Melloddy failing at T2 validation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/zairachem-docker#1]
Hi @miquelduranfrigola 

I have almost completed the refactoring of the train_setup step. It installs zairabase and a bunch of other dependencies, notably melloddy, pandas, rdkit and numpy need to be on the specified versions or they fail.
Despite not getting any particular dependency error anymore, I am unable to make melloddy function properly (I have tried both melloddy 2.3.1 and 3.0.3a0):

I am stuck at this T2 validation, it seems melloddy is not calculating the descriptors file but I am unable to understand why:
```
Input file: ../../tests/osm_bin_smi.csv
Output directory: ../../tests/osm_bin
Direction None
Threshold None
Session file /home/gturon/github/ersilia-os/tests/osm_bin/session.json
Session file /home/gturon/github/ersilia-os/tests/osm_bin/session.json
Session file /home/gturon/github/ersilia-os/tests/osm_bin/session.json
Standardising
Wrote input params to '/home/gturon/github/ersilia-os/tests/osm_bin/data/melloddy/results/standardize_smiles_run_params.json'

Read new config file.
Default reference files from data/reference_set.csv loaded.
Read new key file.
Hashing unit test file /home/gturon/github/ersilia-os/tests/osm_bin/data/melloddy/results/reference_set/T11.csv
Hashing /home/gturon/github/ersilia-os/zairachem-docker/01_train_setup/zairasetup/tools/melloddy/config/example_parameters.json
Hashing /home/gturon/github/ersilia-os/zairachem-docker/01_train_setup/zairasetup/tools/melloddy/config/example_key.json
Hashing version: 3.0.3a
Done.
No reference hash given. Comparison of generated and reference hash keys will be skipped.
Hashing reference data finished after 0.42129159 seconds.
Start standardizing structures.
Check uniqueness of T2.
Schema errors and failure cases:
  schema_context             column           check check_number failure_case index
0         Column  input_compound_id  dtype('int64')         None       object  None
T2 validation failed.
```

**Comment by GemmaTuron** [comment]
Upon discussion we have decided that Melloddy is a liability as it is not maintained (last push over 2y ago). We use mellody to create the folds for the crossvalidation and the standardisation of SMILES:
- Standardisation: to be done with the standardiser package or this [new tool](https://jcheminf.biomedcentral.com/articles/10.1186/s13321-020-00456-1)
- Folds random: random
- Folds by scaffold: using Murcko scaffolds from RDKit and copying the Melloddy  structure
- Folds by lsh (hashing): using Hashed Morgan FPS from RDKIT and copying the Melloddy approach

**Comment by miquelduranfrigola** [comment]
100% agree with this.
